export const episodes = [
  {
    group: "Meet the Cast",
    id: 1,
    episodeNumbers: "01-06",
    episodeList: [
      {
        id: 1,
        pos: 0,
        name: "01 - The Arrival",
        vimeoId: "728917047",
      },
      {
        id: 2,
        pos: 1,
        name: "02 - Let's meet Pete",
        vimeoId: "734106000",
      },
      {
        id: 3,
        pos: 2,
        name: "03 - Namaste, Journey",
        vimeoId: "734106294",
      },
      {
        id: 4,
        pos: 3,
        name: "04 - Soul of Sam",
        vimeoId: "734106504",
      },
      {
        id: 5,
        pos: 4,
        name: "05 - The full Monty",
        vimeoId: "734106753",
      },
      {
        id: 6,
        pos: 5,
        name: "06 - I'm Claudine, Damnit!",
        vimeoId: "734106938",
      },
    ],
  },
  {
    group: "First Night Out",
    id: 2,
    episodeNumbers: "07-12",
    episodeList: [
      {
        id: 7,
        pos: 0,
        name: "07 - What to Wear?",
        vimeoId: "734107133",
      },
      {
        id: 8,
        pos: 1,
        name: "08 - Claudine's Confessional (Community Driven Content)",
        vimeoId: "",
      },
      {
        id: 9,
        pos: 2,
        name: "09 - Doing Lines",
        vimeoId: "734107269",
      },
      {
        id: 10,
        pos: 3,
        name: "10 - Sit on a Crystal",
        vimeoId: "734107442",
      },
      {
        id: 11,
        pos: 4,
        name: "11 - I Love You Guys",
        vimeoId: "734107529",
      },
      {
        id: 12,
        pos: 5,
        name: "12 - Monty's Confessional (Community Driven Content)",
        vimeoId: "",
      },
    ],
  },
  {
    group: "House Reality",
    id: 3,
    episodeNumbers: "13-16",
    episodeList: [
      {
        id: 13,
        pos: 0,
        name: "03 - The Price of Gas",
        vimeoId: "734107677",
      },
      {
        id: 14,
        pos: 1,
        name: "14 - Live Mas",
        vimeoId: "734107785",
      },
      {
        id: 15,
        pos: 2,
        name: "15 - Is it Art?",
        vimeoId: "734107914",
      },
      {
        id: 16,
        pos: 3,
        name: "16 - Ape Love Ape",
        vimeoId: "734108089",
      },
    ],
  },
  {
    group: "Dramarama!",
    id: 4,
    episodeNumbers: "17-23",
    episodeList: [
      {
        id: 17,
        pos: 0,
        name: "Thank you, May I Have Another?",
        vimeoId: "734108377",
      },
      {
        id: 18,
        pos: 1,
        name: "Hall of Shame",
        vimeoId: "734108517",
      },
      {
        id: 19,
        pos: 2,
        name: "House meeting",
        vimeoId: "734108728",
      },
      {
        id: 20,
        pos: 3,
        name: "Sam's Confessional (Community Driven Content)",
        vimeoId: "",
      },
      {
        id: 21,
        pos: 4,
        name: "Brother Bruno/Kryptonite",
        vimeoId: "",
      },
      {
        id: 22,
        pos: 5,
        name: "Pete's Peeved",
        vimeoId: "",
      },
      {
        id: 23,
        pos: 6,
        name: "Pete's Confessional (Community Driven Content)",
        vimeoId: "",
      },
    ],
  },
  {
    group: "The Visits",
    id: 5,
    episodeNumbers: "24-29",
    episodeList: [
      {
        id: 24,
        pos: 0,
        name: "Visitor Scene A",
        vimeoId: "",
      },
      {
        id: 25,
        pos: 1,
        name: "Visitor Scene B",
        vimeoId: "",
      },
      {
        id: 26,
        pos: 2,
        name: "Visitor Scene C",
        vimeoId: "",
      },
      {
        id: 27,
        pos: 3,
        name: "Visitor Scene D",
        vimeoId: "",
      },
      {
        id: 28,
        pos: 4,
        name: "Visitor Scene E",
        vimeoId: "",
      },
      {
        id: 29,
        pos: 5,
        name: "Journey's Confessional (Community Driven Content)",
        vimeoId: "",
      },
    ],
  },
  {
    group: "The ending is near",
    id: 6,
    episodeNumbers: "30-34",
    episodeList: [
      {
        id: 30,
        pos: 0,
        name: "Family Feelings",
        vimeoId: "734836202",
      },
      {
        id: 31,
        pos: 1,
        name: "What I'm trying to Say",
        vimeoId: "",
      },
      {
        id: 32,
        pos: 2,
        name: "You've got Mail",
        vimeoId: "",
      },
      {
        id: 33,
        pos: 3,
        name: "That's all Folks",
        vimeoId: "",
      },
      {
        id: 34,
        pos: 4,
        name: "Where are they now? (Community Driven Content)",
        vimeoId: "",
      },
    ],
  },
];
